# Generated by Django 3.2.6 on 2022-01-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=50)),
                ('market_place', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Alappuzha', 'Alappuzha'), ('Pathanamthitta', 'Pathanamthitta'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), (' Ernakulam', ' Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), (' Kozhikode', ' Kozhikode'), ('Wayanadu', 'Wayanadu'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], default='Thrissur', max_length=30)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('pincode', models.PositiveIntegerField(blank=True, null=True)),
                ('land_mark', models.CharField(blank=True, max_length=100, null=True)),
                ('market_image', models.ImageField(default='default.jpg', upload_to='market_image')),
            ],
        ),
    ]
