# Generated by Django 3.2.9 on 2021-11-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
