# Generated by Django 3.2.9 on 2021-11-18 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211118_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverd_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('packed', 'packed'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='pending', max_length=20),
        ),
    ]
